version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql 
  app:
    # Here, Image name with [docker hub username]/[app_image_name]:[build_tag_version]
    image: masudcsesust04/rails-web-starter:latest 
    restart: always
    volumes:
      # Here, rails-web-starter = docker image root path defined in docker file
      - ./production/config/application.yml:/var/www/rails-web-starter/config/application.yml
      - ./production/config/database.yml:/var/www/rails-web-starter/config/database.yml
      - ./production/public/uploads:/var/www/rails-web-starter/public/uploads
      - ./production/log/production.log:/var/www/rails-web-starter/log/production.log
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "3000"
  web:
    image: nginx:1.14.2-alpine
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.access.log:/var/www/rails-web-starter/log/nginx.access.log
      - ./nginx/nginx.error.log:/var/www/rails-web-starter/log/nginx.error.log
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
